### ISSUE TITLE
Mod crashes with the Aether

### ISSUE THREAD

**Issue by Maks7594** [Johni0702/BetterPortals#628] opened 2022-12-16 16:13 UTC
Just tried loading up my modpack. I don't know if there are any incompatibilities with Betterportals but it only showed an error about some betterportals aether class. I attached the log btw

OS: Win11 22H2
CPU and GPU and RAM: why do you need those ¯\_(ツ)_/¯

[latest.log](https://github.com/Johni0702/BetterPortals/files/10247298/latest.log)

**Comment by Johni0702** [comment] 2022-12-18 21:23
Duplicate of #593

**Closed as not planned by Johni0702** 2022-12-18 21:23 UTC

**Comment by Maks7594** [comment] 2022-12-22 16:59
> Duplicate of #593
searched the entire issues page, and i DIDNT FIND IT SOMEHOW???
