### ISSUE TITLE
I can only go through portals once

### ISSUE THREAD

**Issue by jacobrae** [Johni0702/BetterPortals#191] opened 2019-07-31 05:01 UTC
For some reason I'm only able to go through the portal once and then I can't see through it anymore and I can't go through it so I have to break it and relight the portal to have it work like normal again. On version 0.2.3

**Comment by jacobrae** [comment] 2019-07-31 05:08
Although it works fine for the Twilight Forest portal, just not for Neather and Aether

**Comment by jacobrae** [comment] 2019-07-31 05:12
I also found away to break the Twilight Forest portal by falling through and landing in the portal again creating a loop which stops and ends up making me fall through the world a bit and putting me inside blocks underground in the overworld. After I dug back up it basically had the same effect the other portals were experiencing after I went through once.

**Comment by jacobrae** [comment] 2019-07-31 05:17
https://imgur.com/a/BZindoy I also couldn't break it

**Comment by jacobrae** [comment] 2019-07-31 05:27
https://imgur.com/a/55FV5Vz also the other portals

**Comment by jacobrae** [comment] 2019-07-31 05:32
I was able to go a distance from the portal so it was in unloaded chunks and then go back and it worked again but did the same thing where I couldn't go back through. I was also able to go back and forth in the portal riding an entity just fine, it only doesn't let me go back through if I go through it normally.

**Comment by jacobrae** [comment] 2019-07-31 05:36
https://paste.dimdev.org/etukawuwen.mccrash it doesn't crash probably because of vanilla fix but it gives me this error thing when I go through riding an entity. There's also a list of all the other mods as well if that's helpful.

**Comment by Johni0702** [comment] 2019-07-31 06:41
Probably an interaction with one of the other mods, try removing as many as possible such that you end up with just BP + the incompatible mod(s).

**Comment by RedEchelon** [comment] 2019-08-09 13:17
I was having this exact same issue on 0.2.5 - and I was able to narrow down the incompatibility i was having to Dynamic Stealth. Dynamic stealth's required mod, FantasticLib, doesn't cause the issue on its own, but if i have Forgelin, BP 0.2.5, FantasticLib, and Dynamic Stealth all together, portals break after going through them - the portal itself becomes a solid block which renders pure black instead of a view of the overworld.

As with Jacobrae, riding an entity through seems to work without the portal having to be rebuilt.

**Comment by Johni0702** [comment] 2019-08-09 16:15
@RedEchelon Thanks for tracking this down, it appears to be caused by an issue in Dynamic Stealth (the one linked above, it also affects CubicChunks) which needs to be fixed by them.

**Closed by Johni0702** 2019-08-09 16:15 UTC
Labels: bug, compatibility

**Comment by Laike-Endaril** [comment] 2019-08-10 16:58
Fixed in latest version of DS (087).

Notes:
* Sight angle is not synced when looking through a portal (ie, stuff on the other side of the portal is not seen from the same angle you're facing)
* Non-players can't seem to see through portals
