### ISSUE TITLE
Mobs are rendered but not properly processed through a portal

### ISSUE THREAD

**Issue by Hyxaru** [Johni0702/BetterPortals#374] opened 2019-09-26 13:59 UTC
I tried building a farming setup for pigmen where they would fall through a nether portal, to die to fall damage on the other side. 

What I noticed was that mobs properly fall through the portal, up to a certain distance at which point they froze in midair. If I made them hit a floor before that, they could die normally, but their corpses froze aswell. 

Mobs seem to have no AI ‘on the other side’, but I guess they are somewhat being processed still. I can drop an item through and see it fall. 

If I pass through the portal myself, all the frozen corpses properly disintegrate into smoke and drops, aswell as mobs moving.

Now this all might be an intentional, but maybe undesired limitation to loading the other dimension remotely.

(Same results for with or without using a cubic world)

**Comment by Johni0702** [comment] 2019-09-26 17:04
I'm unable to reproduce what you're describing. I'm dropping pigmen from y=80 through a nether portal into a flat world, they fall until they hit the grass at y=~5, then they die and despawn as expected.

Was running BP 0.3.6 + CC 1003

**Comment by Hyxaru** [comment] 2019-09-27 15:46
I found the interaction that causes this. It is due to Optifine's smooth world option, found under the performance settings. The discription mentions it distributes the internal server load to stabilize FPS.

**Comment by Johni0702** [comment] 2019-09-27 16:15
Hmm, seems plausible but if I throw in OF E3, reset its settings to default (and verify that Smooth World is turned on, which it was), then I'm still unable to reproduce the issue.

**Comment by Hyxaru** [comment] 2019-09-27 19:39
Im using forge 2847, BP 0.3.6, Forgelin 1.8.3 and OF U_E3.
After deleting optionsof, I still get the same issue with what I assume is a clean optifine config.

**Comment by Johni0702** [comment] 2019-09-28 06:04
Would you mind sharing your world (make sure to stand at a place where one can see the issue)?
Also, since it's probably relevant, what's your render distance?

**Comment by Hyxaru** [comment] 2019-09-28 11:02
[Optifine test.zip](https://github.com/Johni0702/BetterPortals/files/3665372/Optifine.test.zip)

I had my render distance at 6 initially, but even at 16 the issue persisted.

**Comment by Johni0702** [comment] 2019-09-29 09:07
Thanks, I can indeed reproduce the issue using your world.

However I've had a look through OF's issue tracker and apparently that's what smooth world is supposed to do: https://github.com/sp614x/optifine/issues/364
It probably wasn't happening in my test world because my overworld and nether coordinates were approximately the same (or close to 0/0/0? which is where BP spawns a fake player), so OF thought I was near the entity at all times.

Given this appears to be intended behavior, I'm going to close this issue and add a note to the OF section of BP's description on CurseForge.

**Closed by Johni0702** 2019-09-29 09:07 UTC
Labels: bug, compatibility
