### ISSUE TITLE
[Mod Interaction] Crash when opening steve's carts Assembler GUI 

### ISSUE THREAD

**Issue by Skaard** [Johni0702/BetterPortals#99] opened 2019-07-09 00:57 UTC
Game crash when opening Cart assembler GUI with an open portal in any of the currently loaded chunks. tried two different versions of steve's carts

java.lang.NullPointerException: Rendering screen
	at net.minecraft.util.math.AxisAlignedBB.func_72326_a(SourceFile:282)
	at de.johni0702.minecraft.betterportals.client.renderer.AbstractRenderPortal$Companion$beforeRender$inPortals$1.apply(AbstractRenderPortal.kt:65)
	at de.johni0702.minecraft.betterportals.client.renderer.AbstractRenderPortal$Companion$beforeRender$inPortals$1.apply(AbstractRenderPortal.kt:27)
	at net.minecraft.world.World.func_175644_a(World.java:3034)
	at de.johni0702.minecraft.betterportals.client.renderer.AbstractRenderPortal$Companion.beforeRender(AbstractRenderPortal.kt:58)
	at net.minecraft.client.renderer.entity.RenderManager.handler$beforeRenderEntity$zzi000(RenderManager.java:597)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java)
	at vswe.stevescarts.guis.GuiCartAssembler.render3DCart(GuiCartAssembler.java:304)
	at vswe.stevescarts.guis.GuiCartAssembler.drawGuiBackground(GuiCartAssembler.java:234)
	at vswe.stevescarts.guis.GuiBase.func_146976_a(GuiBase.java:157)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at vswe.stevescarts.guis.GuiBase.func_73863_a(GuiBase.java:129)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full Error log
[crash-2019-07-08_17.35.20-client.txt](https://github.com/Johni0702/BetterPortals/files/3370722/crash-2019-07-08_17.35.20-client.txt)

**Comment by Johni0702** [comment] 2019-07-09 04:37
Duplicate of #86

**Closed by Johni0702** 2019-07-09 04:37 UTC
