### ISSUE TITLE
Infinite load

### ISSUE THREAD

**Issue by Ibirtem** [Johni0702/BetterPortals#459] opened 2020-01-31 07:53 UTC
When you enter the map there is a new loading screen (Infinite (at this time the game does not even freeze))
Console spam: Received data for unknown dimension
Idk how and why but i have last ver such as Tails and SereneSeasons or another mod. Can it be problem with OTG(9.0) or Mekanism portals in Space Station (Galacticraft)?
p.s. sorry. bad eng

**Comment by Johni0702** [comment] 2020-01-31 10:16
Please attach the full game log. If it's spamming "Received data for unknown dimension", there's likely an error prior to that (otherwise the dimension wouldn't be unknown). The log will also contain detailed info on which mods you're using.

**Comment by Ibirtem** [comment] 2020-01-31 23:01
https://gist.github.com/Ibirtem/8ed8c6e250dc684fb585e8ca3685ad63

**Comment by Johni0702** [comment] 2020-02-01 11:41
Looks like this is probably caused by https://github.com/micdoodle8/Galacticraft/issues/3835.

Though the symptoms appear to be quite different, the following line in the log is printed by the code in question, so it appears to be run for some reason, at which point all bets are off.
```
[01:59:53] [Server thread/INFO] [Galacticraft]: Server attempting to transfer player Ibirtem[view] to dimension 0
```

I'll be closing this issue as the bug needs to be fixed in Galacticraft. If it's still happening after above issue has been fixed, please post an updated log file and I'll reopen this issue and take another look.

**Closed by Johni0702** 2020-02-01 11:41 UTC
Labels: bug, needs more information
