### ISSUE TITLE
Crash with Dynamic Surroundings Mod

### ISSUE THREAD

**Issue by sayys-ouro** [Johni0702/BetterPortals#523] opened 2020-05-21 01:56 UTC
**Mod Version:**

Dynamic Surroundings [1.12.2-3.6.1.0]
OreLib [1.12.2-3.6.0.1]
Better Portals [1.12.2-0.3.7.7]
Shadowsfacts' Forgelin [1.12.2-1.8.4]

**Forge Version:**

MineCraft Forge [1.12.2-14.23.5.2847]

**Link to client log:**

latest: https://pastebin.com/bbvvEf3M
debug: https://pastebin.com/M6A33yhX

**Link to crash log:**

Crash log is not created. In the game, crash information only appears: "An unexpected problem has occurred and the game has crashed. Sorry for the inconvenience.''.

**Description:**

The game crashes without opening the game window. Just click play in the launcher and crash. I only have the Modes: Dynamic Surroundings [1.12.2-3.6.1.0], Better Portals [1.12.2-0.3.7.7], OreLib [1.12.2-3.6.0.1] and Shadowsfacts' Forgelin [1.12.2-1.8.4]. The game with these four mods never starts. I have not tried to change the mod and Forge versions. Please, help me.

**Comment by Johni0702** [comment] 2020-05-21 05:52
Duplicate of #512

**Closed as completed by Johni0702** 2020-05-21 05:52 UTC
