### ISSUE TITLE
Better Portals fails to start with Aether Legacy installed.

### ISSUE THREAD

**Issue by SpookLass** [Johni0702/BetterPortals#577] opened 2020-11-07 19:25 UTC
This might be caused by another mod I have as well, but I have the most recent version of both the Aether and Better Portals and it always fails to start with the two. I know Better Portals has some compatibility issues with VanillaFix, however, I had solved that by naming it _vanillafix instead. Not sure what else would cause this.

**Comment by Johni0702** [comment] 2020-11-08 15:50
Duplicate of #557

**Closed as completed by Johni0702** 2020-11-08 15:50 UTC
