### ISSUE TITLE
Enigmatica 2 Expert - Game Crash

### ISSUE THREAD

**Issue by Emendio** [Johni0702/BetterPortals#524] opened 2020-05-22 14:58 UTC
When I launch E2E from the Twitch launcher with BetterPortals installed (The only other mod I have added is Optifine although the pack runs normally with this) it crashes before even getting to the Mojang loading screen. This then kicks me back to the launcher saying the game crashed although thre is no reason given 
(see image)
![Capture](https://user-images.githubusercontent.com/38014041/82680779-abaa5f00-9c44-11ea-9f0f-de215aed9493.PNG)

I have also attached one of the logs from a session where this crash happened

[2020-05-22-6.log](https://github.com/Johni0702/BetterPortals/files/4668827/2020-05-22-6.log)

**Comment by Johni0702** [comment] 2020-05-22 17:30
Duplicate of #512

**Closed as completed by Johni0702** 2020-05-22 17:30 UTC
