### ISSUE TITLE
Game crash on startup

### ISSUE THREAD

**Issue by TotusTuusMaria** [Johni0702/BetterPortals#552] opened 2020-08-08 03:05 UTC
The game crashes on startup and doesn't provide a pop-up or crash report. I'm running 1.12.2-forge-14.23.5.2854 through the normal Minecraft launcher. Both BP and Forgelin are present. The game starts and runs normally without these two mods but crashes on startup with these mods present. 

The Minecraft launcher open output log displays this when I attempt to start the game:
[MinecraftGameOutput.txt](https://github.com/Johni0702/BetterPortals/files/5044544/MinecraftGameOutput.txt)

I also got this fatal message from the game output when trying to start the game again with the same mods (including BP and Forgelin):
`Process crashed with exit code 1`

I noticed these lines in the output:
`[22:40:26] [main/FATAL] [FML]: A CRITICAL PROBLEM OCCURRED INITIALIZING MINECRAFT - LIKELY YOU HAVE AN INCORRECT VERSION FOR THIS FML
22:40:26.483
[22:40:26] [main/ERROR] [LaunchWrapper]: Unable to launch`

I'm not sure what to do with the info from the above lines. If I should post on the Forge Forums, please just say that.

Modlist:
[Modlist.txt](https://github.com/Johni0702/BetterPortals/files/5044675/Modlist.txt)
AmbientSounds_v3.0.12_mc1.12.2.jar
Baubles-1.12-1.5.2.jar
betterportals-0.3.7.7.jar
Bloodmoon-MC1.12.2-1.5.3.jar
Chameleon-1.12-4.1.3.jar
Chisel-MC1.12.2-1.0.2.45.jar
coroutil-1.12.1-1.2.37.jar
CreativeCore_v1.10.16_mc1.12.2.jar
CTM-MC1.12.2-1.0.2.31.jar
DarknessLib-1.12.2-1.1.0.jar
DeathFinder-v1.0.1-1.12.2.jar
DenseMetals-1.12.2-2.0.0.30.jar
EpicSiegeMod-13.167.jar
Farseek-1.12-2.5.jar
Forgelin-1.8.4.jar
furniture-6.3.1-1.12.2.jar
HardcoreDarkness-MC1.12.2-2.0.jar
InventoryTweaks-1.64+dev.151.jar
IvToolkit-1.3.3-1.12.jar
jei_1.12.2-4.15.0.297.jar
OptiFine_1.12.2_HD_U_F5(3).jar
Pam's+HarvestCraft+1.12.2zg.jar
raiders-1.12.2-3.0.9.jar
RecurrentComplex-1.4.8.2.jar
SereneSeasons-1.12.2-1.2.18-universal.jar
Sound-Physics-1.12.2-1.0.9.jar
StorageDrawers-1.12.2-5.4.2.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
TreeChopper-1.12.2-1.2.4.jar
twilightforest-1.12.2-3.10.1013-universal.jar
useful_backpacks-1.12.2-1.5.3.59.jar
u_team_core-1.12.2-2.2.5.147.jar
VanillaFix-1.0.10-150.jar
weather2-1.12.1-2.6.12.jar
weeping-angels-46.jar
wildnature-1.2.jar
worleycaves-1.5.1.jar
[1.12.2]+SecurityCraft+v1.8.19.3.jar

Thank you for any and all help.

Edit1: I removed Optifine and launched, game still crashed on startup

**Comment by SlimefrogSocial** [comment] 2020-08-17 21:23
Having same problem, is caused by VanillaFix, please patch I can't remove VanillaFix for it is used almost every time the game is loaded.

EDIT: #499

**Comment by Johni0702** [comment] 2020-08-27 05:51
Duplicate of #547

**Closed as completed by Johni0702** 2020-08-27 05:51 UTC
