### ISSUE TITLE
Split screen caused by better portals

### ISSUE THREAD

**Issue by jameslc92** [Johni0702/BetterPortals#615] opened 2022-04-24 11:54 UTC
I am running minecraft 1.12.2. I had some other mods installed but have removed everything except better portals and forgelin and the issue remains.
When I make a nether portal, the screen splits into 4 parts, with 1 quarter showing the normal view, and another quarter showing what I imagine is a render of the other world (e.g., the nether if you are in the overworld, or the overworld if you are in the nether). It is very weird. 
Any ideas on how to resolve this? Playing on an Acer predator 2019 with Windows 10.

Screenshot below is having just entered the nether, and looking back towards the portal.
![screenshot](https://user-images.githubusercontent.com/72658734/164975059-460a8ce3-7b9a-4b98-acd4-9c24a8d5073d.png)

**Comment by Johni0702** [comment] 2022-04-24 13:31
Duplicate of #541

**Closed as completed by Johni0702** 2022-04-24 13:31 UTC
