### ISSUE TITLE
Incompatibility with Dynamic Surroundings

### ISSUE THREAD

**Issue by BlueHedgy** [Johni0702/BetterPortals#535] opened 2020-06-16 14:25 UTC
So upon testing to launch my personal mod pack
I found out that better portal always exit with code -1 when launched with Dynamic surrounding
I don't think the log helps much but you can find it in attachment
[crash log BP DS.txt](https://github.com/Johni0702/BetterPortals/files/4787098/crash.log.BP.DS.txt)

**Comment by Johni0702** [comment] 2020-06-16 15:33
Duplicate of #512

**Closed as completed by Johni0702** 2020-06-16 15:33 UTC
