### ISSUE TITLE
Better portals crash

### ISSUE THREAD

**Issue by Bluubies** [Johni0702/BetterPortals#571] opened 2020-10-10 21:21 UTC
Hello so i have had been trying to this this issue on my own but i always came up with nothing

I first started by making another mod called "VanillaFix" and made it run before betterportals and that let me boot Minecraft

Then i had to install "Shadowfacts' Forgelin" and once i did that it just loads up and the mod that tells me what happened if it crashes says that "BetterPortals" is the issue.

Ill leave some links and Screenshots to all the mods i have installed to see if anyone else has the same issue or a fix.

I have had Better Portals work in the past with even more mods so i dont think the amount of mods is the issue?

[crash-2020-10-10_17.14.41-client.txt](https://github.com/Johni0702/BetterPortals/files/5360192/crash-2020-10-10_17.14.41-client.txt)

![ccc4f459755fe9b29e24baae9cba8a38](https://user-images.githubusercontent.com/43254583/95665280-e7bf5d00-0b1c-11eb-8a50-c2f5a5d6ddd0.png)

**Comment by Johni0702** [comment] 2020-10-11 09:46
Duplicate of #557

**Closed as completed by Johni0702** 2020-10-11 09:46 UTC
