### ISSUE TITLE
Mod Doesn't play well on servers

### ISSUE THREAD

**Issue by M201425935** [Johni0702/BetterPortals#96] opened 2019-07-08 18:19 UTC
So, from what I can gather, the mod really hates running on dedicated servers.
I've got some of the error log when creating a portal, as the portal appears black but you can't go through it and that's it, I've also noted that on reload of the server this causes it to crash when a player joins. I've tried removing the mods that it lists here, but once I do that, the list changes. to note, I removed Astral Sorcery, Zombie Awareness (has problems with it's required util) and a few other things. 
[BetterPortals-Error.txt](https://github.com/Johni0702/BetterPortals/files/3369730/BetterPortals-Error.txt)

**Comment by Johni0702** [comment] 2019-07-08 21:13
Duplicate of #38

**Closed by Johni0702** 2019-07-08 21:13 UTC
