### ISSUE TITLE
Cubic Chunks compatability

### ISSUE THREAD

**Issue by border999** [Johni0702/BetterPortals#469] opened 2020-02-17 07:59 UTC
hello, have you looked into possible compatibility issues with Cubic Chunks? It appears the update you pushed out in the last day isn't handling CC very well. I teleported from one dimension to another, and the dimension never loaded. may I ask you to look into it? if you need more info, I'll provide what I can

**Comment by border999** [comment] 2020-02-17 08:00
It may be pertinent to hop on the Cubic Chunks discord and talk to it's maker. See where things might be going wrong.

**Comment by Johni0702** [comment] 2020-02-17 09:55
Eh, I'm familiar with CC and have quite a bit of code specifically for it, I just didn't bother to test yesterday's change with it because the change doesn't directly affect any of it (or at least I though so).
Will look into it.

**Comment by Johni0702** [comment] 2020-02-17 11:37
Hmm, I'm actually having difficulties reproducing the issue in my development environment (CC 1033).
Could you please give detailed steps as to what you did and also attach the log file?

This is what I tried:
1. Create new flat world with CC enabled
2. `/tp 0 5 0`
3. Build and activate nether portal nearby
4. `/forge setdim @p 1` to go to the end
5. `/forge setdim @p 0` to go back to the overworld, arriving next to the existing portal

**Comment by Johni0702** [comment] 2020-02-17 13:34
I made a stupid mistake in the yesterday's update which broke all third-party dimension changes unless you're either using Sponge or have "Enhance third-party transition" enabled.

During above test I've had the latter enabled, so I didn't ran into the issue, but I guess you're using neither.
If that's indeed the case, you may close this issue and subscribe to https://github.com/Johni0702/BetterPortals/issues/455 to get notified when I fix it (already have it fixed in dev but I'll try to fix a few other issues before releasing the next version later today).

**Comment by Johni0702** [comment] 2020-02-17 16:11
The underlying issue should be fixed in 0.3.7.7. If you're still having trouble with BP+CC, please attach the full game log and instructions on how to reproduce it.

**Closed by Johni0702** 2020-02-17 16:11 UTC
Labels: bug, compatibility, old version
