### ISSUE TITLE
Botania issue?

### ISSUE THREAD

**Issue by WarriorGamingserv** [Johni0702/BetterPortals#110] opened 2019-07-12 12:49 UTC
so, was building a custom modpack and i added this mod to add some 'realisim' so to say, and a problem happend with it and botania, as it was working fine before i added botania, whenever i look at the portal the world looses color, for example the grass would become completely gray, i do have optifine, but even removing it doesn't fix the problem, my versions are

Better Portals 0.1.6
Optifine 1.12.2 HD U E3
Botania r1.10-361
forgelin 1.8.3

Here are some examples of how it looks like
![2019-07-12_08 48 56](https://user-images.githubusercontent.com/39961255/61129222-edde0e00-a481-11e9-9738-36bc39c372d4.png)
![2019-07-12_08 49 01](https://user-images.githubusercontent.com/39961255/61129224-ef0f3b00-a481-11e9-9b76-0d7551803054.png)

**Comment by Johni0702** [comment] 2019-07-15 13:09
Cannot reproduce, also tried placing a few (possibly significant) things down but still no colorless grass:
![](https://i.johni0702.de/WtHeG.png)

Forge 2838
BP 1.0.6
Shadowfacts' Forglin 1.8.3
Botania r1.10-361
Baubles 1.5.2

**Comment by Johni0702** [comment] 2019-07-16 21:08
Closing in favor of #131 which has more (though unfortunately still not enough) details.

**Closed by Johni0702** 2019-07-16 21:08 UTC
Labels: bug, compatibility
