### ISSUE TITLE
Mod denies game from starting

### ISSUE THREAD

**Issue by pickle-low** [Johni0702/BetterPortals#566] opened 2020-09-24 18:12 UTC
I tried to add the BetterPortals mod to my modpack, but whenever I try to start with it on, it just refuses to. I've removed Optifine, SereneSeasons is on the right version for it to work, so I don't know what's going on.

When I try to launch minecraft, the "minecraft game output" says this:

14:11:15.806
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
14:11:15.806
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
14:11:15.806
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.security.AccessController.doPrivileged(Native Method)
14:11:15.806
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
14:11:15.806
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
14:11:15.806
[java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
14:11:15.806
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
14:11:15.806
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
14:11:15.817
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
14:11:15.817
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.getConstructor0(Class.java:3075)
14:11:15.817
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.newInstance(Class.java:412)
14:11:15.817
[java.lang.ThreadGroup:uncaughtException:1061]: 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
14:11:15.817
[java.lang.ThreadGroup:uncaughtException:1061]: 	... 18 more
14:11:15.841

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
14:11:15.841
Process crashed with exit code 1

**Comment by Johni0702** [comment] 2020-09-24 18:55
That log is incomplete, I can't tell you more from that.

**Comment by Redd56** [comment] 2020-09-25 00:25
Upload the entire log to pastebin or mc.logs

**Comment by pickle-low** [comment] 2020-09-25 03:45
here, is this this good?
https://pastebin.com/NEdbQhFA

**Comment by pickle-low** [comment] 2020-09-25 03:56
Alright, is this good?
https://pastebin.com/di7phRyi

Also, I feel its also worth mentioning that a popup appears on the launcher itself that says "Game Crashed: An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. Exit Code: 0"

**Comment by Johni0702** [comment] 2020-09-25 06:04
Duplicate of #547

**Closed as completed by Johni0702** 2020-09-25 06:04 UTC
