### ISSUE TITLE
Add support Stargate Network mod

### ISSUE THREAD

**Issue by PixelmonPRO** [Johni0702/BetterPortals#419] opened 2019-11-26 07:38 UTC
Hello! I suggest adding support for portals (stargates) from the mod Stargate Network.
Page mod on Curse: https://www.curseforge.com/minecraft/mc-mods/stargate-network
Source code: https://github.com/AlmuraDev/SGCraft

**Comment by Johni0702** [comment] 2019-11-26 08:32
Duplicate of #244

**Closed by Johni0702** 2019-11-26 08:32 UTC
