### ISSUE TITLE
Incompatibility with Waystones mod

### ISSUE THREAD

**Issue by Neubenutzer** [Johni0702/BetterPortals#527] opened 2020-06-04 09:55 UTC
The [Waystones](https://www.curseforge.com/minecraft/mc-mods/waystones) mod can teleport you cross-dimensional, but with betterportals, the game crashes with the error message: `java.lang.IllegalStateException: Player changed world without us noticing. Did some third-party mod do something weird?`

**Comment by Johni0702** [comment] 2020-06-04 10:40
Duplicate of #401

**Closed as completed by Johni0702** 2020-06-04 10:40 UTC
