### ISSUE TITLE
Idea: Betweenlands Better Portal.

### ISSUE THREAD

**Issue by TheMCSpacePro** [Johni0702/BetterPortals#182] opened 2019-07-27 22:45 UTC
Betweenlands is a epic mod with a buttload on content, 99.9% of it is in another dimention, behind a loading screen. I am asking that you add support for this mod. Please...

Just to make your life easier here, here is a link to the mod's sourcecode on Github:
https://github.com/Angry-Pixel/The-Betweenlands

**Comment by Johni0702** [comment] 2019-07-28 06:00
Duplicate of #175

**Closed by Johni0702** 2019-07-28 06:00 UTC

**Comment by TheMCSpacePro** [comment] 2019-07-28 13:00
Didn't know, sorry
