### ISSUE TITLE
Better portals made customnpcs look like pong paddles! Forge 2838, 1.12.2 

### ISSUE THREAD

**Issue by Sageking10** [Johni0702/BetterPortals#146] opened 2019-07-19 15:09 UTC
![2019-07-19_11 06 02](https://user-images.githubusercontent.com/48606472/61545467-8c83e500-aa15-11e9-812a-c99b42faa6d3.png)
This happens when i go back and forth between dimensions, with the customnpcs mod installed.

**Comment by Johni0702** [comment] 2019-07-19 15:27
Which version of BP / CustomNPCs?

**Comment by Sageking10** [comment] 2019-07-19 15:30
CustomNPCs_1.12.2(30Jan19)
betterportals-0.1.6

**Comment by Johni0702** [comment] 2019-07-19 15:35
Duplicate of #42

**Closed by Johni0702** 2019-07-19 15:35 UTC
