### ISSUE TITLE
Mixin Crash

### ISSUE THREAD

**Issue by GamingMidi** [Johni0702/BetterPortals#565] opened 2020-09-16 23:53 UTC
Everytime I launch my mod pack, It crashes before the window even shows up... And I get this crash: https://pastebin.com/7nZtKiB5

All the mods I am using have been updated to their latest updates.

**Comment by Johni0702** [comment] 2020-09-17 12:02
Duplicate of #547

**Closed as completed by Johni0702** 2020-09-17 12:02 UTC
