### ISSUE TITLE
Looking at the portal makes the world look grey

### ISSUE THREAD

**Issue by LCTMarti** [Johni0702/BetterPortals#131] opened 2019-07-16 16:44 UTC
As soon as the portal is built and being looked at/rendered everything, the sky, leaves, blocks except dirt, goes grey.

**Comment by Johni0702** [comment] 2019-07-16 16:51
You might want to give [this](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) a read.
Also sounds like a duplicate of #110.

**Comment by LCTMarti** [comment] 2019-07-16 17:02
Yeah It's pretty much the same thing, though I have a lot more mods in my pack, that's why I didn't drop any files. It looks like you could not reproduce the bug if I read that correctly. Is there anything that could help solving this issue? A log maybe?

**Comment by Johni0702** [comment] 2019-07-16 17:19
The log's unlikely to contain a direct hint as to what is causing the issue. Rendering issues tend to be harder to debug, so priority number one should be putting me into a state where I can reproduce it on my machine.
Things which will help to do that:
- Try narrowing it down to as few mods as possible (so few that I can reasonably install them to reproduce the issue) and then list all of them with exact versions (in know for a fact that the other thread doesn't list them all because they're missing, e.g. baubles)
- Make sure it's reproducible in an empty flat world without structures (i.e. literally only grass, dirt and bedrock around). If it's not, then I'll need the world to reproduce it.
- Also try using BP 0.2 if you aren't already. Stuff changed and if this happens to have gotten fixed as a side-effect, then we're done already.

**Comment by LCTMarti** [comment] 2019-07-16 18:19
In a flat world everything's working fine. I tried out some mods that I thought could cause this issue without success so far. Problem is I've got 160+ mods in my pack so it's hard to find that one mod that could cause it. What's more likely to cause this issue: a structure mod or something like huds, ftb utilites and so on?

**Comment by Johni0702** [comment] 2019-07-16 18:33
Really hard to tell, with rendering stuff it could really be anything. Though the fact that it doesn't happen in a flat world could be a clue: it's probably something in your world (how about newly generated worlds?) or something which is different between a flat and normal world (e.g. biomes).

Instead of trying to find the one mod, throw out half of them, test, and if the issue continues to exist, repeat, otherwise try the other half (might be that more than one mod's required). That way you should in theory (ignoring dependencies between mods and the fact that more than one might be required) be able to narrow it down to a single mod within ~12 runs.

**Comment by LCTMarti** [comment] 2019-07-16 19:32
Hmmmm...
After starting and closing Minecraft about 30-35 times I've got a result, but one, that doesn't quite satisfy me. It should be caused by either blood magic, shadowfacts forgelin (which comes with blood magic) or cofh world. Newest version of all those mods, plus forge. 
Neither Blood Magic and SF Forgelin nor COFH World on their on cause this issue. I hope this helps..

**Comment by Johni0702** [comment] 2019-07-16 20:09
I've tried running
```
  betterportals-0.2.1
  BloodMagic-1.12.2-2.4.1-103
  CoFHWorld-1.12.2-1.3.1.7-universal
  Forgelin-1.8.3
  Guide-API-1.12-2.1.8-63
```
about five times in two different worlds (what exactly do you mean by "not everytime"?) but I'm still unable to reproduce the issue.
One notable thing though is that BloodMagic throws errors into the log for me even when ran on its own. Looks like [that](https://github.com/WayofTime/BloodMagic/issues/1325) issue on their tracker and since it has to do with shaders, it'd be a prime candidate for causing this issue (or rather not cause it since it's broken for me).

**Comment by LCTMarti** [comment] 2019-07-16 20:13
Well I guess I'll have to remove Blood Magic then until that's fixed. Btw, little side note and then I'll close this issue don't worry: the purple frames inside the nether portal have lighting issues, nothing too big though so not worth investigating in that unless you instantly know what I mean or what's causing it and why does creating/loading the nether portal freeze the game since the newest version?

**Comment by Johni0702** [comment] 2019-07-16 20:29
I'd prefer you keep the issue open until it's actually fixed. By now it contains quite a lot of possibly useful info.

No idea what you mean by the light issues, they look fine to me (might be another mod interaction?). I'd have to see screenshots.

The freezing might just be an oversight on my part. During development (unless it's for OF compatibility) I'm running the game purely on my CPU without any GPU (for reasons), so I'm always getting <10 fps anyway, so performance regressions tend to go unnoticed.
I've just tested it and I can indeed notice a short freeze when opening a portal for the first time. I'll be looking into that (tracking it in #133).

**Comment by Johni0702** [comment] 2019-07-16 20:52
Hm, I've just fixed the BloodMagic error myself but I'm still unable to reproduce this issue.

**Comment by LCTMarti** [comment] 2019-07-16 20:57
newest forge? all mods on their newest version as well

**Comment by LCTMarti** [comment] 2019-07-16 20:57
maybe its something with the minecraft default video settings as well

**Comment by Johni0702** [comment] 2019-07-16 21:02
Yes, that's Forge 2838. I just tried resetting all mod and game settings but, aside from very annoying music, there appears to be no difference.

**Comment by LCTMarti** [comment] 2019-07-16 21:04
are you using the twitch desktop app?

**Comment by Johni0702** [comment] 2019-07-16 21:07
No, I'm using MultiMC, I'd be really surprised if the launcher had any influence on it though.
I'll be leaving it as is for now. Maybe someone else who's also experiencing the issue is able to provide us with the important detail.

**Comment by blueblaise** [comment] 2019-11-19 01:22
possibly check your video settings

**Comment by blueblaise** [comment] 2019-11-19 03:23
silents gems causes this issue every time from what I've noticed

**Comment by Johni0702** [comment] 2019-11-19 11:53
@blueblaise 
To confirm, are you saying that you're able to reproduce this with just BP 0.3.7.1, Forgelin, SilentsGems 2.8.22+327 and SilentLib 3.0.13+167?

**Comment by blueblaise** [comment] 2019-11-19 23:37
yes i can double check though

**Comment by blueblaise** [comment] 2019-11-20 00:12
no not just that i think i might have missed a few mods

**Comment by blueblaise** [comment] 2019-11-20 00:32
so now i can 100% confirm electrobob's wizardry 4.2.1, BP 0.2.6, Forgelin 1.8.3, SilentLib 3.0.13+167, SilentsGems 2.8.22+327, and Forge 14.23.5.2847. i have gotten it to work every time with these mods. i think it is three different simple graphics/shader not working together electrobobs graphics is for some of the spells, the silentsgems graphics is for the chaos nodes and weapon specials, and the better portals graphics is obviously for the portals.

**Comment by Johni0702** [comment] 2019-11-20 08:08
> electrobob's wizardry 4.2.1, BP 0.2.6, Forgelin 1.8.3, SilentLib 3.0.13+167, SilentsGems 2.8.22+327, and Forge 14.23.5.2847

How about wizardry 4.2.5 and BP 0.3.7.1?
Also, does there have to be anything nearby (aside from a portal), or rather, can you reproduce this in an empty flat world as well?

**Comment by blueblaise** [comment] 2019-11-23 00:28
idk i can try. sorry that i am not consistant

**Comment by blueblaise** [comment] 2019-11-23 00:40
![2019-11-22_18 36 11](https://user-images.githubusercontent.com/57926135/69469589-42aa6300-0d57-11ea-8800-9be5e44dccb7.png)
![2019-11-22_18 36 28](https://user-images.githubusercontent.com/57926135/69469590-4342f980-0d57-11ea-8364-0582d67d29ca.png)
it seems to affect your side of the world because if you are in the nether everything gets darker and in the overworld everything goes into greyscale

**Comment by blueblaise** [comment] 2019-11-23 01:40
i just checked with the newer versions of both mods and it still does the same thing

**Comment by Johni0702** [comment] 2019-11-25 15:18
I'm able to reproduce this and AFAICT it's caused by this issue in Electroblob's Wizardry: https://github.com/Electroblob77/Wizardry/issues/170

Going to close this under the assumption that OP had that mod installed as well.

**Closed by Johni0702** 2019-11-25 15:18 UTC
Labels: bug, compatibility, help wanted

**Comment by blueblaise** [comment] 2019-11-25 20:44
well actually you need to have buth silents gems and electroblobs wizardry before this issue occures

**Comment by Johni0702** [comment] 2019-11-25 21:50
Yeah, I know, I tried myself as well.
Doesn't change the fact the the **source** of the issue is almost certainly in Wizardry's code.
BP, when combined with silent gems, merely triggers the issue (and only in combination with whatever silent gems is doing, probably because the bug isn't a trivial one). If you look through the issue I linked, you'll see at least two other combination of mods which trigger the issue.

I'm not saying there definitely isn't an issue in siltent gems or BP, merely that we know there to definitely be an issue in Wizardry, so instead of searching for one in the other two, let's wait till we know it isn't the one in Wizardry (i.e. till that one is fixed).
