### ISSUE TITLE
Game crashes on start (fails to launch)

### ISSUE THREAD

**Issue by SpencerMeow** [Johni0702/BetterPortals#528] opened 2020-06-07 03:30 UTC
Whenever I try to launch the game, even with Forgelin, it gives an error message "Game crashed: "An unexpected issue occurred and the game has crashed, We're sorry for the inconvenience." It doesn't generate any crash report as far as I can tell, and I'm not using any mods with it. I'm launching it from Twitch.

**Comment by Johni0702** [comment] 2020-06-07 08:56
Will need the game log then, otherwise I can derive about as much from the error message as you can.

**Comment by Jetprism** [comment] 2020-06-30 05:25
https://paste.ubuntu.com/p/xGfsnrkv2C/

**Comment by Jetprism** [comment] 2020-06-30 05:26
that's my log,same issue here

**Comment by Johni0702** [comment] 2020-06-30 07:29
Duplicate of #512

**Closed as completed by Johni0702** 2020-06-30 07:29 UTC
