### ISSUE TITLE
Dimensional Doors compatibility bug causing infinite loading screen

### ISSUE THREAD

**Issue by skullface2587** [Johni0702/BetterPortals#482] opened 2020-03-05 01:52 UTC
#459 am a mod pack creator / tester and I noticed a compatibility bug with the dimensional doors mod and the better portals mod. This bug causes an infinite loading screen that I had left running for 30 minutes and nothing happens. When I saw this I loaded up a test world with only the Better Portals and the Dimensional Doors mods. And I had the same result. I also checked to see if both were the latest version of 1.12.2. And they were. My theory is that the Better Portals mod is confused between the Dimensional Doors portals and the regular portals.

**Comment by Johni0702** [comment] 2020-03-05 09:50
Duplicate of #428

**Closed as completed by Johni0702** 2020-03-05 09:50 UTC
