### ISSUE TITLE
When using Idō, player model goes invisable when swimming.

### ISSUE THREAD

**Issue by TheMCSpacePro** [Johni0702/BetterPortals#357] opened 2019-09-16 21:57 UTC
When using Idō, in 3rd person your character is invisible while swiming. Someone had reported this to Kaydax with no results, so I let them know that I'd report this issue to you.
Source code: https://github.com/Kaydax/Ido

**Comment by Johni0702** [comment] 2019-09-16 22:04
Duplicate of #200

**Closed by Johni0702** 2019-09-16 22:04 UTC
