### ISSUE TITLE
Weird Sneaking bug with RandomPatches

### ISSUE THREAD

**Issue by itsEvil** [Johni0702/BetterPortals#259] opened 2019-08-18 19:31 UTC
Sneaking is buggy. 
Before opening a portal its fine. 
When you open it or render the other side your sneaking will bug out. I still works as in you cant fall off blocks but it makes your screen jitter. Please fix, cos this mod amazing but with this bug i can't stand it.

**Comment by Johni0702** [comment] 2019-08-18 21:06
Cannot reproduce. https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by Dalethium** [comment] 2019-08-18 21:38
I actually was able to reproduce this on my modpack, however there are far too many mods to be able to effectively help you. I'll link the list in hopes that someone else can cross compare the lists.

https://pastebin.com/xGKg4eRu

**Comment by OverInfrared** [comment] 2019-08-20 15:22
I have reproduced this bug on Texkit 3, so naturally i copied down all of the mods into a internal server; removed mods 1 by 1 until I found the mod that does this effect. AND the culprit IS!

RandomPatches. (randompatches-1.12.2-1.17.2.1)
cross referenced with the post above me he has it to.

I don't know why this happens but I know it is this mod!

**Comment by OverInfrared** [comment] 2019-08-20 15:25
Oh and you have to go through the portal for the bug to start. (At least for me)

**Comment by Johni0702** [comment] 2019-08-20 16:01
Thank you very much for taking the time to narrow this down.
I can indeed reproduce the issue with BP 0.2.6 + RandomPatches 1.17.2.1 and will be looking into it.

For my convenience:
https://www.curseforge.com/minecraft/mc-mods/randompatches
https://github.com/TheRandomLabs/RandomPatches/tree/1.12/

**Comment by Johni0702** [comment] 2019-08-20 16:10
This is caused by RandomPatches' smooth eye height patch which in its current implementation assumes there to only be a single world.
You can work around the issue until it's fixed (needs fixing in RandomPatches, I'll be opening an issue over there shortly) by going to `Mod Options -> RandomPatches -> Config -> Client-sided` and setting `Smooth eye level changes` to `false` or by changing the equivalent config option in RandomPatches' config file.

**Comment by OverInfrared** [comment] 2019-08-20 16:18
lol! I was just about to tell you that. I was looking through the config. Forgot that you can just go into the options. 

I think its the backport from 1.13 smooth crouch.

After I turned that off it stopped happening, but I still had smoothing on.

**Comment by Johni0702** [comment] 2019-08-21 07:17
Fixed in RandomPatches 1.12.2-1.18.1.1

**Closed by Johni0702** 2019-08-21 07:17 UTC
Labels: bug, compatibility
