### ISSUE TITLE
Game crash when loading

### ISSUE THREAD

**Issue by c4tgrl** [Johni0702/BetterPortals#580] opened 2020-11-29 16:54 UTC
Mods are in log
I am running version 1.12.2
I am using MultiMC launcher
When I disable Better Portals it fixes this issue
Log: https://pastebin.com/qBerG02v

**Comment by Johni0702** [comment] 2020-11-29 18:06
Duplicate of #547

**Closed as completed by Johni0702** 2020-11-29 18:06 UTC
