### ISSUE TITLE
Getting stuck in Twilight Forest portal

### ISSUE THREAD

**Issue by AlienXtream** [Johni0702/BetterPortals#248] opened 2019-08-16 06:22 UTC
some strange stuff happens when i try and enter the TF portal. at first the generated portal in the forest did not load correctly (had to re form the portal a couple times). after getting back to the overworld trying to re enter the forest caused me to enter what i could only describe as a "limbo" state, which resolved itself after a short time by putting me underground. im assuming being spawned at the equivilent coordinates of the TF portal, though in the overworld.

**Comment by Johni0702** [comment] 2019-08-16 07:16
Please attach the game log.

**Comment by AlienXtream** [comment] 2019-08-16 08:58
so.. i go and try to reproduce the issue in order to generate a new log (dont know wich one is the previous log).... would you beleive that the issue is not happening again.... will keep testing it and if it happens again i will immediatly send the section of the log from when it happened. if you could lable this as "needs more info" or "needs reproducing" or something to that effect. that or just close the issue for now until im able to reproduce it

**Comment by lag42** [comment] 2019-08-18 14:16
i can entirely reproduce this, additionally when it happens in survival mode i get a death message saying i died of fall damage

[here's](https://gist.github.com/lag42/b9c66718c5268cac590707da7d25fb81) my latest.log

**Comment by Johni0702** [comment] 2019-08-18 14:29
@lag42 
Please remove any third-party mods you have, so we can be sure they aren't related to this issue.
Also make sure you're not running into #253 to not complicate matters.
Then, post an updated log and explain step by step what you did, what happened and what you expected to happen.

> i get a death message

Make sure to mention when this happens in above steps, it's not in the log.

> it seems it needs some space for it to drag the player down to

I don't understand, what do you mean? Who's dragging the player where?

**Comment by AlienXtream** [comment] 2019-08-18 14:39
i assume by "draging" they are meaning the game moving the player in ways contrary to what the player has input. as for dying, while i did not have that spesific outcome, i was waring darksteel boots which negate falldamage when powered so that makes sense

**Comment by lag42** [comment] 2019-08-18 15:16
@Johni0702 

> Make sure to mention when this happens in above steps, it's not in the log

it happens when i jump in the portal

> i don't understand, what do you mean? Who's dragging the player where?

i meant when the game was moving the player underground, i thought it was pretty clear that was what i was referring to

> Please remove any third-party mods you have, so we can be sure they aren't related to this issue.
Also make sure you're not running into #253 to not complicate matters.
Then, post an updated log and explain step by step what you did, what happened and what you expected to happen.

1. make a default type world with creative mode and cheats on

2. make a twilight forest portal in creative mode

3. go into survival mode then jump in the portal

4.  jump into the portal repeatedly until you get a death message but don't die if the twilight forest portal isn't completely solid

5. wander around and you should eventually be teleported to an underground space in the overworld

what i expected to happen: to stay in the twilight forest and not get teleported to an underground space in the overworld

what happened; i got teleported to an underground space in the overworld

improved log [here](https://gist.github.com/lag42/83b1f43714a28d40e1cdd80f0c62cbf8) (CTM and patchouli are listed as required dependencies for twlight forest on the curseforge page so those stay)

**Comment by Johni0702** [comment] 2019-08-18 16:22
Alright, I'm able to reproduce what you're describing and I see two issues here:
- Under yet to be determined conditions, the server can disagree about collision when going through a twilightforest portal (possibly other types as well?) which will cause the player to constantly get teleported back, building up fall distance until at some point they do pass through, touch the ground and die.
- Death isn't registering on the client if it happens in the time between the client using a portal and the server acknowledging that action. This is almost certainly caused by the same fundamental flaw as #151.

**Comment by lag42** [comment] 2019-08-18 17:16
i think you've found a separate issue, i have noticed i've been teleported up to the portal once, but not repeatedly like you're describing

**Comment by Johni0702** [comment] 2019-08-18 17:21
I'd guess it's the same issue anyway considering it's disagreeing at least once for you as well and the rest of the symptoms are identical.
It might be that for some reason (possibly related to #151) your client player wasn't repeatedly teleported while, invisible to you, the server player was. For all I know (I only tried once), the behavior I'm seeing might even be really rare while the one you're seeing is the common one.

**Comment by AlienXtream** [comment] 2019-08-18 22:11
despite the variance in symptoms i think this could indeed be the cause. a new approach to twilight portals would be best imo. the collest effect would be to have the TF upside down but that causes more issues. perhaps just increasing the offset for the portal so its 100% impossible to end up in a loop under normal circumstances. i would say 4-5 blocks would be good

**Comment by Johni0702** [comment] 2019-08-31 08:29
The collision checking issue has been fixed in 2f57b4e.
The various changes required for fixing the death issue are documented in #151.
All of those changes have landed in BP 0.3.

**Closed by Johni0702** 2019-08-31 08:29 UTC
Labels: bug, compatibility
