### ISSUE TITLE
Crash during launch. Error with The Aether

### ISSUE THREAD

**Issue by Leofric118** [Johni0702/BetterPortals#568] opened 2020-10-01 20:09 UTC
[crash-2020-10-01_21.45.30-client.txt](https://github.com/Johni0702/BetterPortals/files/5314493/crash-2020-10-01_21.45.30-client.txt)
this i my crash report, I hope you can help
Thanks in advance for any assistance.

**Comment by Johni0702** [comment] 2020-10-01 21:55
Duplicate of #557

**Closed as completed by Johni0702** 2020-10-01 21:55 UTC
