### ISSUE TITLE
Crash when loading a world with preexisting portal

### ISSUE THREAD

**Issue by CactusDuud** [Johni0702/BetterPortals#109] opened 2019-07-11 22:44 UTC
https://pastebin.com/s47v3Scw

**Comment by Johni0702** [comment] 2019-07-12 11:08
Duplicate of #104 
Please follow the instructions given over there to help fixing that bug (comparing their list of mods to yours will make it a lot easier as well).

**Closed by Johni0702** 2019-07-12 11:08 UTC
