### ISSUE TITLE
(Enhancement) Interacting with the other side of portals without going through

### ISSUE THREAD

**Issue by TheMCSpacePro** [Johni0702/BetterPortals#502] opened 2020-04-10 17:42 UTC
This is simple. It would allow one to, from the overworld, break a block in the nether simply by doing it through a portal. Another mod, which is 1.15.2, also does this - that mod being Immersive Portals, so I know it's possible. It'd be nice to see your own spin on this in 1.12.2!

**Comment by TheMCSpacePro** [comment] 2020-04-10 20:09
Alright, after looking at the "Implementation Details" of Immersive Portals, here's what it had to say about this: 
"Vanilla assumes that only the chunks near player will be loaded so ClientChunkManager use a fixed size 2d array to store chunks. I change it into a map so the chunk storage is not limited to the area near player. Similar thing also applies to BuiltChunkStorage.

Vanilla only allows one client world to be present at a time but this mod breaks this assumption. This mod will create faked client world when it's firstly used. When ticking remote world or processing remote world packet, it will switch the world field of MinecraftClient and then switch back."

**Comment by Johni0702** [comment] 2020-04-10 20:52
Duplicate of #10

**Closed as completed by Johni0702** 2020-04-10 20:52 UTC
