### ISSUE TITLE
Bug with morph mod

### ISSUE THREAD

**Issue by Cyanoure** [Johni0702/BetterPortals#176] opened 2019-07-24 17:28 UTC
You see on the screenshot. And the morphed character isn't animated.
![2019-07-24_19 24 02](https://user-images.githubusercontent.com/30216303/61814593-af186280-ae48-11e9-95fa-73f4ea3de756.png)
![2019-07-24_19 24 14](https://user-images.githubusercontent.com/30216303/61814594-af186280-ae48-11e9-88ef-bfcc2d37586c.png)
Sorry for my bad English.

**Comment by Johni0702** [comment] 2019-07-24 20:50
If this is caused by what I think it is, then it should have been fixed by one of the major changes in BP 0.2 (same one as #77). Could you please try the most recent (0.2.3) BP version?

**Closed** 2019-08-22 12:10 UTC
Labels: bug, compatibility, old version
