### ISSUE TITLE
Portals invisible at certain angles

### ISSUE THREAD

**Issue by yezhiyi9670** [Johni0702/BetterPortals#472] opened 2020-02-17 11:42 UTC
Minecraft version: 1.12.2  
Optifine version: HD U F5

Nether portals and Aether Legacy portals can be invisible (but still show particles) at certain angles. Maybe standing close to the portal and turning your head reproduces the issue.

Also Aether Legacy portals can be inverted (i.e. The side which should show the Aether shows the Overworld, and the side which should show overworld shows the Aether) when the player is standing accurately in the middle of it (consider the portal a glass pane, and the player is between the front side and the back side), but it doesn't affect the teleporting behavior (it's only a rendering issue). This causes the vision slightly flash when the player enters Aether, and can rarely generate a `CCL caught an exception rendering a block` error. Note it seems that only one side of the portal can cause this issue (in my case, I was entering the portal from west to east in Overworld).

**Comment by Johni0702** [comment] 2020-02-17 13:26
This sounds like three separate things (to me at least, I can totally see how they might seem to be the same for someone not familiar with BP's inner working, so I'm not blaming you for putting them together).
I'll reply to each of them and then close this issue. Please open three new issues, one for each of the sections quoted, and include the reply to my questions over there.

> Nether portals and Aether Legacy portals can be invisible (but still show particles) at certain angles. Maybe standing close to the portal and turning your head reproduces the issue.

Sounds like: https://github.com/Johni0702/BetterPortals/issues/4
Can you confirm that this happens only when one part of the portal is in a different chunk than the player?
If it does, then there's no need to open a new issue for this one.
If that's not the case, can you reproduce it without third-party mods (so just BP and Forgelin)?

> Also Aether Legacy portals can be inverted (i.e. The side which should show the Aether shows the Overworld, and the side which should show overworld shows the Aether) when the player is standing accurately in the middle of it (consider the portal a glass pane, and the player is between the front side and the back side), but it doesn't affect the teleporting behavior (it's only a rendering issue). This causes the vision slightly flash when the player enters Aether

Can this not happen with nether portals? There shouldn't be any significant technical difference between nether and aether portals with BP.
Can you reproduce it without third-party mods (so just BP and Forgelin)?

> and can rarely generate a CCL caught an exception rendering a block error.

This is likely caused by some third-party mod which didn't expect there to be multiple worlds at the same time. Please attach the full game log and I'll likely be able to tell you which one and possibly also report it to them.

> Note it seems that only one side of the portal can cause this issue (in my case, I was entering the portal from west to east in Overworld).

It is unclear to me if this refers to the visual issue or the crash (visual issue would make the most sense to me). Please include it in whichever issue it belongs to.

**Closed by Johni0702** 2020-02-17 13:26 UTC

**Comment by yezhiyi9670** [comment] 2020-02-17 13:58
OK. I've tried those under third-party-less environment.

The first issue (the first quote) only occurs on cross-chunk portals, so the issue is a duplicate of #4. But hope you can find out a way to fix it (although I haven't heard any ways yet except hacky rendering).

The second one is not reproduceable under third-party-less environment, and Optifine is also not the reason. I'm going to find it out later.

The third situation is rare. Maybe I can just ignore it.

**Comment by yezhiyi9670** [comment] 2020-02-17 14:12
Things became strange: #4 and the Inverted Portal Issue now can't happen on my Minecraft with a lot of mods at all!
