### ISSUE TITLE
Game crashes during the loading process

### ISSUE THREAD

**Issue by userr123456789** [Johni0702/BetterPortals#575] opened 2020-10-26 19:24 UTC
It says NoSuchFieldException: procesor

Crash log: https://pastebin.com/yZ7jNjbv

**Comment by DrUltraLux** [comment] 2021-03-14 11:45
I am having the same problem.

**Comment by Johni0702** [comment] 2021-03-14 18:11
Duplicate of #547

**Closed as completed by Johni0702** 2021-03-14 18:11 UTC
