### ISSUE TITLE
Game wont start when using Dynamic surroundings

### ISSUE THREAD

**Issue by XenoTerra** [Johni0702/BetterPortals#549] opened 2020-07-27 12:14 UTC
using better portals version 0.3.7.7 for MC 1.12.2 and dynamic surroundings 1.12.2-3.6.1.0 causes a crash

**Comment by suprstarrd** [comment] 2020-08-05 20:49
I can reproduce this issue.

Although it makes sense, Dynamic Surroundings would be trying to make sounds from the ender dragon/nether.

**Comment by Kuraiko55** [comment] 2020-08-16 17:30
Same issue here with exact same mod versions.

**Comment by Johni0702** [comment] 2020-08-27 05:51
Duplicate of #547

**Closed as completed by Johni0702** 2020-08-27 05:51 UTC
