### ISSUE TITLE
Issue with Better portals and chisels and bits

### ISSUE THREAD

**Issue by Panduso** [Johni0702/BetterPortals#213] opened 2019-08-06 15:53 UTC
When i use chisels and bits and have little tiles and better portals installed at the same time when i place then remove bits, i can't break or place normal blocks without reloading the save.

**Comment by Johni0702** [comment] 2019-08-06 18:18
Does this happen even when no portals are around or do you have to have portals loaded or do you have to have used one?

**Comment by Panduso** [comment] 2019-08-06 18:29
it happens when portals are around

Minecraft version: 1.12.2
Forge version: forge-14.23.5.2838
Better portals: 0.2.5
Chisels & Bits: 14.33 (actually the maker of chisels and bits has retired from mod making)
LittleTiles: v1.5.0-pre157_mc1.12.2
WorldEdit: 1.12.2

**Comment by Johni0702** [comment] 2019-08-06 18:32
Are all those mods required for reproducing the issue? I.e. if you remove any of them, does it no longer happen?

The WorldEdit version is just the MC version, that doesn't seem right.
Please also list versions of dependencies (e.g. LittleTiles requires CreativeCore, BP requires Forgelin).

**Comment by Panduso** [comment] 2019-08-06 18:40
Worldedit doesn't matter its just those three, remove little tiles, the issue is gone, remove better portals, the issue is gone

**Comment by Panduso** [comment] 2019-08-06 18:43
WAit, nope i removed little tiles now there's only chisels and bits and better portals. the thing still happens

**Comment by Panduso** [comment] 2019-08-06 18:46
so its only Chisels and bits and Better Portals that create the issue

**Comment by Panduso** [comment] 2019-08-08 13:36
hello?

**Comment by Johni0702** [comment] 2019-08-08 13:49
Hi!

You've answered all the questions I had and I'm able to reproduce the issue. I haven't yet had time to look into the cause.

**Comment by Panduso** [comment] 2019-08-08 14:06
Oh ok! thank you, i'm glad you are able to look into it afterwards :D

**Comment by Johni0702** [comment] 2019-08-12 10:33
@Panduso A proper fix for this needs to happen in C&B, the above workaround should make the problem disappear under most circumstances.
If it's still happening for you, post the log and describe exactly what you're doing to make it happen and which portals are rendered at which parts of the process (enabling Debug View in BP settings will allow you to clearly tell if a portal is being rendered). This is relevant because C&B does a significant chunk of its logic during rendering (not really the place where it should happen but that's where it currently is).

**Comment by Johni0702** [comment] 2019-10-27 19:25
Closing because C&B1 is no longer being worked on (and fixing this issue is very much non-trivial), so the workaround in BP is all there's going to be.
Its successor C&B2 (MC 1.14) should not have the same issue.

**Closed by Johni0702** 2019-10-27 19:25 UTC
Labels: bug, compatibility, waiting for third-party, wontfix
