### ISSUE TITLE
Game crash when loading Mystcraft Dimensions

### ISSUE THREAD

**Issue by AbstractFox** [Johni0702/BetterPortals#414] opened 2019-11-18 17:18 UTC
There seems to be an incompatibility with Mystcraft. I loaded a void world using a Mystcraft book, and my game crashed. When I rejoined, I loaded the dimension, but when I went back to the overworld my game crashed again, and I couldn't open my world.
(Thank god it was a creative bug testing world for my modpack)

**Comment by Johni0702** [comment] 2019-11-19 11:47
Duplicate of #330

**Closed by Johni0702** 2019-11-19 11:47 UTC
