### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by WarriorGamingserv** [Johni0702/BetterPortals#448] opened 2020-01-19 01:00 UTC
Hello, i'd like to start off by saying i love your mod and here's the crash report i got
[crash-2020-01-18_19.58.40-client.txt](https://github.com/Johni0702/BetterPortals/files/4082118/crash-2020-01-18_19.58.40-client.txt)

**Comment by Johni0702** [comment] 2020-02-08 19:06
Duplicate of #432

**Closed by Johni0702** 2020-02-08 19:06 UTC
Labels: bug
