### ISSUE TITLE
Crash on start please help

### ISSUE THREAD

**Issue by TheOneChris** [Johni0702/BetterPortals#531] opened 2020-06-11 22:16 UTC
[latest.log](https://github.com/Johni0702/BetterPortals/files/4767605/latest.log)
 game crashes on start can't figure out why I do have 
![mods 4](https://user-images.githubusercontent.com/60333802/84444352-93a87880-ac0f-11ea-8646-c15cac054ce9.PNG)
![mods 3](https://user-images.githubusercontent.com/60333802/84444353-94410f00-ac0f-11ea-81a4-bb0f0c8d14eb.PNG)
![mods 2](https://user-images.githubusercontent.com/60333802/84444355-94d9a580-ac0f-11ea-92e3-b2d29699a02f.PNG)
![mods 1](https://user-images.githubusercontent.com/60333802/84444356-94d9a580-ac0f-11ea-91ab-efd953eb1af7.PNG)

attached is the latest crash log and 4 images of my twitch mod list

I can't figure out where the conflict is if there is one.

**Comment by Johni0702** [comment] 2020-06-11 23:29
Duplicate of #517

**Closed as completed by Johni0702** 2020-06-11 23:29 UTC
