### ISSUE TITLE
Incompatibility with Dimensional Doors

### ISSUE THREAD

**Issue by jeqlusty** [Johni0702/BetterPortals#625] opened 2022-08-25 23:46 UTC
Hi, I was recently playing with a modpack that includes both betterportals and dimensionaldoors, and whenever I enter a dimensional door, my game crashes. I did some digging and I found out that the reason for the crash was because of betterportals. I tried to see if it was other mods interfering as well, so I put these two in a profile alone and the same problem happened. Sorry if this has already been covered.

**Comment by Johni0702** [comment] 2022-09-12 15:25
Duplicate of #428

**Closed as not planned by Johni0702** 2022-09-12 15:25 UTC
