### ISSUE TITLE
Weird portal cloning bug

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [Johni0702/BetterPortals#151] opened 2019-07-20 12:33 UTC
I just went through the portal multiple times and then it cloned me. I was getting pushed around without me pressing any button.
I attempted to reproduce it, but it did not happen again.
![image](https://user-images.githubusercontent.com/27149563/61578675-ead6c380-aafa-11e9-975d-adac59afdf1d.png)
Server Log:
```
[14:22:17] [Server thread/WARN] [minecraft/NetHandlerPlayServer]: ErdbeerbaerLP moved too quickly! 13.47313286255024,9.0,29.72815505770329
[14:22:17] [Server thread/WARN] [betterportals/portal]: Ignoring use portal request from EntityPlayerMP['ErdbeerbaerLP'/0, l='world', x=8,48, y=71,00, z=-3,25] because they have an outstanding teleport.
[14:22:17] [Server thread/WARN] [betterportals/portal]: Ignoring use portal request from EntityPlayerMP['ErdbeerbaerLP'/0, l='world', x=8,48, y=71,00, z=-3,25] because they have an outstanding teleport.
```

After leaving the (localhost) server, vanillafix caught this crash: https://paste.dimdev.org/ikapaxehad.rb

**Comment by Johni0702** [comment] 2019-07-20 12:38
How close are those portals to each other and what's your server's view-distance?

**Comment by ErdbeerbaerLP** [comment] 2019-07-20 12:48
`view-distance=10`
The portals are very close (37 blocks) to each other

**Comment by Johni0702** [comment] 2019-07-21 16:31
Appears to be reliably reproducible:
1. Build two linked teleporters next to each other (same chunk)
2. Flying away until they unload
3. Fly back (and hope it doesn't crash from another bug which I've already fixed in dev)
4. Notice how one of the two portals will have your player's movements slightly delayed (because the other side is actually a different world and you're seeing server-lag)
5. Go through that portal
6. You are two

**Comment by Johni0702** [comment] 2019-07-21 20:25
Upon initial investigation, I've come to the conclusion that this is caused by a fundamental flaw in how BP currently does the seamless transition into other dimensions and fixing it will be **very** complicated.
Unfortunately I cannot come up with a good workaround either, so I've instead added a disclaimer on the CF page stating that short-range teleporters are essentially broken at the moment.

**Closed** 2019-08-29 10:55 UTC
Labels: bug
