### ISSUE TITLE
Crouching makes the screen jitter

### ISSUE THREAD

**Issue by AngelSkyheart** [Johni0702/BetterPortals#291] opened 2019-08-27 22:25 UTC
I added Better Portals 0.2.6 to my All The Mods 3 5.12.3 server. It works well, though I've noticed a few small issues, the primary one being that after installing this mod to both my client and server, my character now jitters in place whenever I crouch, the camera that is. It does the same for my friend on the server, but it doesn't look like his character model is shaking when he crouches, but the screen still shakes. It's really disconcerting. Is there a way to fix this? Edit: It does the same thing when I sleep. It constantly looks like I'm crouching and uncrouching really fast when I crouch and sleep.

Two other smaller issues I've noticed since installing this. 

1. My mine turtle from computercraft in the nether leaves behind a copy of itself sometimes. Like, not a full copy, just a shell. Trying to right click it makes it disappear, and left clicking just breaks it. It's not even consistent either. When it appears, it stays, but it doesn't seem to have any rhyme or reason why it shows up in the first place.

2. The mod that lets you pass the night via sleeping with a majority 'vote' seems to count each player twice now after installing this mod. So despite my only being on the server, it passes the sleep vote with a 1 out of 2 players sleeping, and when my friend is on, he has to sleep too when I do, because it somehow thinks there's 4 players on the server now, and it requires a minimum 50% for the sleep to work. It's kind of annoying.

**Comment by Johni0702** [comment] 2019-08-28 05:32
Duplicate of #259 

For the other two issues, please open separate tickets so they can be tracked separately.
Also for 2 please check which mod you're using, I wouldn't be surprised if there are multiple mods which do that.

**Closed by Johni0702** 2019-08-28 05:32 UTC
