### ISSUE TITLE
conflict with better portals and aroma's mining dim.

### ISSUE THREAD

**Issue by KroniQPlayer** [Johni0702/BetterPortals#134] opened 2019-07-17 04:40 UTC
never mind, using BP 0.1.6 and just saw the other issue posted, will update first then report if still same problem

**Comment by Johni0702** [comment] 2019-07-17 06:44
Duplicate of #127 

Feel free to reply over there once you've tried it.

**Closed by Johni0702** 2019-07-17 06:44 UTC
