### ISSUE TITLE
BP cant render the portals correctly with shaders

### ISSUE THREAD

**Issue by RazorWolvendom** [Johni0702/BetterPortals#630] opened 2023-03-12 19:54 UTC
it seems that it only works with no shaders at all (off) (mod settings are default)

but not with the Internal one:
<img width="857" alt="ScreenShot_20230312205117" src="https://user-images.githubusercontent.com/44827474/224569760-09d6c7b0-92fd-4210-89ce-f9f2a886af7e.png">

neither with any other shaders like Chocapic13_V9:
<img width="635" alt="ScreenShot_20230312205220" src="https://user-images.githubusercontent.com/44827474/224569781-fed27201-7617-4118-a5f9-9c31fa8e222c.png">

but still functions normally to load it seamless when passing thru

**Comment by Johni0702** [comment] 2023-03-26 11:55
Duplicate of #409

**Closed as not planned by Johni0702** 2023-03-26 11:55 UTC
