### ISSUE TITLE
Crash in multyplayer

### ISSUE THREAD

**Issue by Mattwenty** [Johni0702/BetterPortals#84] opened 2019-06-15 21:47 UTC
When I try to join the server with this mod enabled (client-side/server-side) the server crashes. 
And when I created the nether portal, without leaving the server, it wasn't loading the nether world.
In singleplayer it works very well with the same mods.
I have crash reports

[crash-2019-06-14_20.37.00-server.txt](https://github.com/Johni0702/BetterPortals/files/3293580/crash-2019-06-14_20.37.00-server.txt)

I have also server logs if you need

**Comment by Mattwenty** [comment] 2019-06-15 22:14
I found the cause: it is incompatible with JourneyMap (Server-side)

**Comment by Mattwenty** [comment] 2019-06-15 22:19
Here's the log: 

```
00:13:16] [Server thread/INFO] [journeymap]: Mat2nty joining dimension -1
[00:13:17] [Server thread/INFO] [journeymap]: Sending log in packet.
[00:13:17] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.EntityJoinWorldEvent@2e73eaeb:
java.lang.NullPointerException: null
	at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:39) ~[ForgeEvents.class:1.12.2-5.5.4]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1206) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) [oo.class:?]
	at de.johni0702.minecraft.betterportals.server.view.ServerViewManagerImpl.createView(ServerViewManagerImpl.kt:74) [ServerViewManagerImpl.class:?]
	at de.johni0702.minecraft.betterportals.server.view.ServerViewManager$DefaultImpls.createView$default(ServerViewManager.kt:30) [ServerViewManager$DefaultImpls.class:?]
	at de.johni0702.minecraft.betterportals.common.entity.AbstractPortalEntity.func_184178_b(AbstractPortalEntity.kt:445) [AbstractPortalEntity.class:?]
	at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:458) [os.class:?]
	at net.minecraft.entity.EntityTracker.func_85172_a(EntityTracker.java:392) [ol.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:162) [ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165) [ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[00:13:17] [Server thread/ERROR] [FML]: Index: 3 Listeners:
[00:13:17] [Server thread/ERROR] [FML]: 0: HIGHEST
[00:13:17] [Server thread/ERROR] [FML]: 1: ASM: net.minecraftforge.common.ForgeInternalHandler@66524e8e onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[00:13:17] [Server thread/ERROR] [FML]: 2: NORMAL
[00:13:17] [Server thread/ERROR] [FML]: 3: ASM: journeymap.server.events.ForgeEvents@1b12a7b2 on(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[00:13:17] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:762) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
	at journeymap.server.events.ForgeEvents.on(ForgeEvents.java:39) ~[ForgeEvents.class:1.12.2-5.5.4]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_ForgeEvents_on_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1206) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058) ~[oo.class:?]
	at de.johni0702.minecraft.betterportals.server.view.ServerViewManagerImpl.createView(ServerViewManagerImpl.kt:74) ~[ServerViewManagerImpl.class:?]
	at de.johni0702.minecraft.betterportals.server.view.ServerViewManager$DefaultImpls.createView$default(ServerViewManager.kt:30) ~[ServerViewManager$DefaultImpls.class:?]
	at de.johni0702.minecraft.betterportals.common.entity.AbstractPortalEntity.func_184178_b(AbstractPortalEntity.kt:445) ~[AbstractPortalEntity.class:?]
	at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:458) ~[os.class:?]
	at net.minecraft.entity.EntityTracker.func_85172_a(EntityTracker.java:392) ~[ol.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:162) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165) ~[ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more
[00:13:17] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: C:\Users\Matteo\Desktop\Server [FORGE]\.\crash-reports\crash-2019-06-16_00.13.17-server.txt
[00:13:17] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[00:13:17] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[00:13:17] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[00:13:17] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/overworld
[00:13:17] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save world
[00:13:17] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/the_nether
[00:13:17] [Server thread/WARN] [betterportals]: View de.johni0702.minecraft.betterportals.server.view.ServerViewImpl@2baf6d49 has a refCnt of 1 even though its world is unloaded!
[00:13:18] [Server thread/INFO] [FML]: Unloading dimension 0
```

**Comment by Johni0702** [comment] 2019-07-08 21:13
Duplicate of #38

**Closed by Johni0702** 2019-07-08 21:13 UTC
Labels: bug, compatibility
