### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by JotaRata** [Johni0702/BetterPortals#573] opened 2020-10-23 01:11 UTC
Minecraft won't start at all with BP installed, Exception log says:

`Exception in thread "main" [20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader.fail(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader.access$100(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator.access$700(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator$2.run(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.AccessController.doPrivileged(Native Method)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.ServiceLoader$1.next(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.newInstance(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.SecurityException: class "org.spongepowered.asm.service.ServiceInitialisationException"'s signer information does not match signer information of other classes in the same package

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.checkCerts(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.preDefineClass(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.defineClass(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.access$100(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.AccessController.doPrivileged(Native Method)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.getConstructor0(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.newInstance(Unknown Source)

[20:38:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 19 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
`

Mod installed:

1. Better Portals - 0.15
2. Forgelin-1.8.3
3. DynamicTrees-1.12.2-0.9.7
4. SoundFilters-0.11_for_1.12
5. DynamicSurroundings-1.12.2-3.6.1.0
6. Streams-1.12-0.4.4
7. CreativeCore_v1.10.16_mc1.12.2
8. ItemPhysic_Full_1.4.34_mc1.12.2
9. Craftable+Saddles[1.12]-1.3
10. betteranimals-1.12.2-5.3.0
11. Reforged-Mod-1.12
12. realrender-1.2.3
13. PlayerAPI-1.12.2-1.0
14. SmartRender-1.12.2-2.3-RC2
15. SmartMoving-1.12.2-16.4-RC3
16. OreLib-1.12.2-3.6.0.1
17. OptiFine_1.12.2_HD_U_F5

Curseforge doesnt mention any requirements, so what is wrong?

**Comment by Johni0702** [comment] 2020-10-23 08:22
Duplicate of #547

**Closed as completed by Johni0702** 2020-10-23 08:22 UTC
