### ISSUE TITLE
crash on startup exit code 0

### ISSUE THREAD

**Issue by Yachtea** [Johni0702/BetterPortals#574] opened 2020-10-24 16:00 UTC
i never used this mod before but it seems like a ton of fun well anyway i run it and it instantly crashes on startup with exit code 0 i remove it and then its starts 

what can i do please i want this mod to work

**Comment by Johni0702** [comment] 2020-10-24 17:52
Duplicate of #570

**Closed as completed by Johni0702** 2020-10-24 17:52 UTC
