### ISSUE TITLE
Galacticraft enter dimension bug

### ISSUE THREAD

**Issue by tabr** [Johni0702/BetterPortals#467] opened 2020-02-14 01:35 UTC
1.12.2, SMP, Forge, version latest,  0.3.7.5.
It teleports back to "earth" and server crash.
when uninstall mod - all is good.
https://pastebin.com/8XNWxju9

**Comment by Johni0702** [comment] 2020-02-14 09:21
Duplicate of #421

**Closed by Johni0702** 2020-02-14 09:21 UTC
