### ISSUE TITLE
Game crashes when entering overworld from nether

### ISSUE THREAD

**Issue by theessman** [Johni0702/BetterPortals#216] opened 2019-08-06 21:33 UTC
Whenever I try to place about 3 portals and I enter the overworld from the nether my game crashes. Its the only mod I have enabled. The error is: java.lang.NullPointerException: Unexpected error. This may be due to the Tardis Glitch. The screen turns to the same color as the nether sky when I crash.
[crash-2019-08-06_14.25.09-client.txt](https://github.com/Johni0702/BetterPortals/files/3474236/crash-2019-08-06_14.25.09-client.txt)

**Comment by Johni0702** [comment] 2019-08-07 11:33
Is this reliably reproducible? If so, please stand in front of the portal in question and upload your world so I can try to reproduce it on my machine. Best to also tell me your render distance in that case, since it's likely relevant.

I'm assuming you're referring to the glitch which allows one to remove all portal blocks (and by extension the frame) but still keep the portal entity alive. If so, that shouldn't cause any issues as long as you don't have two portals occupying the same block.

**Comment by theessman** [comment] 2019-08-09 04:58
Here's the world!
[New World--20190806-160632.zip](https://github.com/Johni0702/BetterPortals/files/3484818/New.World--20190806-160632.zip)
My render distance is twelve.
Just try walking through the portal and back
Sorry it took so long to respond.

**Comment by Johni0702** [comment] 2019-08-11 22:29
I unfortunately wasn't able to reproduce the issue with the given world.
However, based on the symptoms, I strongly suspect that it's caused by the same bug as #221 which should be fixed with 0.2.6. Could you please check if 0.2.6 fixes your issue as well?

**Comment by theessman** [comment] 2019-08-13 20:47
I tried 0.2.6 and it doesn't seem to crash.

**Closed** 2019-08-13 21:15 UTC
Labels: bug, old version
