### ISSUE TITLE
The game crashed whilst initializing game

### ISSUE THREAD

**Issue by MaruChan-FV** [Johni0702/BetterPortals#600] opened 2021-05-11 08:11 UTC
Error: java.lang.NoClassDefFoundError: de/johni0702/minecraft/betterportals/impl/aether/common/blocks/BlockBetterAetherPortal
Exit Code: -1

**Comment by Johni0702** [comment] 2021-05-11 08:45
Duplicate of #593

**Closed as completed by Johni0702** 2021-05-11 08:45 UTC
