### ISSUE TITLE
Adding the mod causes an Exit Code:0 error

### ISSUE THREAD

**Issue by Wolf7104** [Johni0702/BetterPortals#570] opened 2020-10-07 07:22 UTC
I added this mod to my modlist, but when I try to launch the game, it immediately crashes with an Exit Code:0 error. What could be causing this? I'm using Twitch to manage my mods and I'm on 1.12.2. Thanks in advance.

**Comment by TheLordMrRat** [comment] 2020-10-23 16:23
The same happens to me

**Comment by jetblade** [comment] 2020-11-03 01:38
same

**Comment by ekiplier** [comment] 2020-11-10 02:51
### The same is happening to me.
Here's a screenshot I took of what happened after launching the game:

![Captura de ecrã 2020-11-10 024850](https://user-images.githubusercontent.com/74121461/98621510-50a61a80-22ff-11eb-9494-2557fd34be08.png)


### I think it's a mod incompatibility so I'm also uploading a screenshot of my mods folder

![Captura de ecrã 2020-11-08 004505](https://user-images.githubusercontent.com/74121461/98621596-8d721180-22ff-11eb-935f-049d583a46a2.png)

### Also here's the logs:
[debug.log](https://github.com/Johni0702/BetterPortals/files/5514562/debug.log)
[latest.log](https://github.com/Johni0702/BetterPortals/files/5514564/latest.log)

**Comment by Johni0702** [comment] 2020-11-12 12:09
Duplicate of #547

**Closed as completed by Johni0702** 2020-11-12 12:09 UTC
Labels: needs more information
