### ISSUE TITLE
Incompatibility with Albedo and StellarSky

### ISSUE THREAD

**Issue by PeasantUnit** [Johni0702/BetterPortals#120] opened 2019-07-15 16:53 UTC
My guess is that there is no way of creating a compatibility between those mods, but I'll still report them here anyway.

StellaySky and BetterPortals causes random crashes.

Albedo and BetterPortals causes light issues in any possible scenario while using the third person camera (F5).

**Comment by Johni0702** [comment] 2019-07-15 18:19
There isn't any particular reason why those two (especially stellar sky) couldn't work with BP (at least for the basic stuff, Albedo working across portals is probably asking for too much).

For me Albedo causes portals to not be see-through except at certain angles (I've got an idea for what might be causing this) and spams the logs.
Upon placing a creative Botania mana pool, the world suddenly becomes darker overall but other than that, colored lighting seem to behave as expected.

One stellar sky issue is being tracked in #85.
Stellar Sky seems to be outdate on CurseForge though. It's latest version there is 0.5.3.2 but its source code shows the latest version to be 0.5.4.1. Is there an official site with a more recent download?
I usually wouldn't mind using the old one but the file where the crash originates has changed significantly between those versions.

**Comment by Johni0702** [comment] 2019-07-15 18:49
After looking at Albedo for a moment, I've reported what I think are the causes of the issues on Albedo "issue tracker", so I'm closing this issue now.
If you've got crashes with stellar sky other than the one linked above, please open new issue for those and provide crash reports, etc.

**Closed by Johni0702** 2019-07-15 18:49 UTC
