### ISSUE TITLE
Game won't launch with the recent version on Tekxit modpack (probably other packs aswell)

### ISSUE THREAD

**Issue by Umitrix** [Johni0702/BetterPortals#210] opened 2019-08-05 17:52 UTC
[debug.log](https://github.com/Johni0702/BetterPortals/files/3468753/debug.log)
[latest.log](https://github.com/Johni0702/BetterPortals/files/3468754/latest.log)

**Comment by Johni0702** [comment] 2019-08-05 18:03
Duplicate of #179

**Closed by Johni0702** 2019-08-05 18:03 UTC
