### ISSUE TITLE
Client crashing when disconecting from server

### ISSUE THREAD

**Issue by BarryHarton** [Johni0702/BetterPortals#462] opened 2020-02-08 13:41 UTC
It seems this crash only happens when a player logs off when a portal is being rendered, Im not sure how I can fix this.

Here is the crash report
https://paste.dimdev.org/lacuteqoxi.mccrash

**Comment by Johni0702** [comment] 2020-02-08 16:23
Duplicate of #432

**Closed by Johni0702** 2020-02-08 16:23 UTC
