### ISSUE TITLE
Can't re-enter portals

### ISSUE THREAD

**Issue by UnoriginalUmbrella** [Johni0702/BetterPortals#281] opened 2019-08-25 12:37 UTC
So when I go into a portal and die, it teleports me to the overworld, and I can go inside the portal. If I die again, the same thing. However, after re-entering the portal a third time, on the other side is nothing and I can't go through it. The only way to fix this Is by quitting and loading the world again.

**Comment by Johni0702** [comment] 2019-08-25 13:01
Indeed. Tbh I'm kind of surprised that I'm able to reliably reproduce this.
It appears like the portal is linked to itself after the second death (at least visually).
Interestingly not even reloading by moving far away will fix it, one has to completely quit the world.

**Comment by border999** [comment] 2019-08-26 01:10
Incorrect, the issue can also be corrected by breaking the portal and and restarting it. @Johni0702

**Comment by Johni0702** [comment] 2019-08-26 05:40
@border999 I don't see what's incorrect. If you break and re-light it, then it's a different portal. This whole issue deals with one single portal only.

**Comment by border999** [comment] 2019-08-26 06:23
oh, I wasn't aware it was considered that way. My apologizes

**Comment by Johni0702** [comment] 2019-08-31 08:12
This appears to be fixed in BP 0.3 (most likely because of 0a30809).

**Closed by Johni0702** 2019-08-31 08:12 UTC
Labels: bug
