### ISSUE TITLE
Game can't even start with BetterThirdPerson mod Forge 1.12.2

### ISSUE THREAD

**Issue by DainXOR** [Johni0702/BetterPortals#629] opened 2023-01-12 04:17 UTC
When tries to load the game from the launcher, at some point it stops and shows up this dialog:
![image](https://user-images.githubusercontent.com/65270757/211974759-2c81e965-4324-4e23-95e7-a77cd287b5e4.png)

Edit: This also seems to happen with Dynamic Surroundings, Vanilla fix...

betterportals-0.3.7.7

[BetterThirdPerson-Forge-1.12.2-1.9.0](https://pastebin.com/UXx25Vhv)
[DynamicSurroundings-1.12.2-3.6.1.0](https://pastebin.com/BvDgrLWj)
[VanillaFix-1.0.10-150](https://pastebin.com/56yUJYvu)

**Comment by FluffyKat43** [comment] 2023-08-22 20:16
BetterThirdPerson messes with how third person movement is handled. It has never worked with Vivecraft and probably never will as they directly conflict for some reason

**Comment by DainXOR** [comment] 2023-08-22 20:20
> BetterThirdPerson messes with how third person movement is handled. It has never worked with Vivecraft and probably never will as they directly conflict for some reason 

Understandable, but why dynamic surroundings? Is it possible to make those two work?

And i guess vanilla fix won't work for the same reason as BetterThirdPerson, so no reason to mention it.

**Comment by FluffyKat43** [comment] 2023-08-22 21:44
VanillaFix dosen't even work at all letalone with Vivecraft, but Dynamic Surroundings is a bit wierd.
Try using it and Vivecraft by itself and check the logs given (Best done with Modrinth App because it can show live logs - if you have a second monitor you can see it doing things in real-time which helps a lot)

**Comment by DainXOR** [comment] 2023-08-22 21:55
Yeah, that's what weirds me out, maybe that fix can be possible without being too traumatic

**Comment by FluffyKat43** [comment] 2023-08-22 21:56
Yeah

Sent from my Bell Samsung device over Canada’s largest network.
________________________________

**Comment by Johni0702** [comment] 2023-08-26 07:47
Duplicate of #560

**Closed as not planned by Johni0702** 2023-08-26 07:47 UTC
