### ISSUE TITLE
Three Visual Errors

### ISSUE THREAD

**Issue by IdrisQe** [Johni0702/BetterPortals#365] opened 2019-09-23 10:51 UTC
Three bugs to report here, pretty sure at least 2/3 of them are mod interactions.

1. When crouching with Nimble and RandomPatches installed, and looking into a portal, the entire portal view stays at the same point on screen, meaning it seems to sink into the portal, as despite you crouching, the view remains stationary relative to your screen. This is likely due to crouching not updating the player's "position" information, so the portal doesn't adjust its fake player-camera or whatever it uses to get the inner view.

2. With Smart Animations on in Optifine (NOTE: I have yet to test extensively to make sure this is the culprit), when looking through a portal, animated textures are stationary and not animated, such as fire, water, etc. This is probably because Optifine disables the animations when the player isn't looking at them, and it can't tell that the player can see into a dimension that they aren't currently inside.

3. Sometimes when moving around, the portal view will jitter a bit. This is likely due to packets containing information on the player's relative position being dropped, as I've been getting console-spammed with such messages.
`[03:39:21] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraft.network.play.client.CPacketConfirmTeleport@726456c7
[03:39:21] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraft.network.play.client.CPacketPlayer$PositionRotation@67423708
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@3de592ce
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@68975090
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@69717e75
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@7cb16e31
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@5ea42f8f
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@7b70415d
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@26e5c57
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@7027b23e
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@7317dc0
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@d4a8c3a
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@43d6fcfd
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@707a7c8d
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@f5d41a3
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@bea109b
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@24f689cc
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@49b31d2
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@4a991b2d
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@490de439
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@1207407
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@26a5e28b
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@17a21d72
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@67f57168
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@66485934
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@27c5279d
[03:39:22] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@1be4a0ec
[03:39:46] [Client thread/INFO] [betterportals/view]: Swapping main view ClientState for world 0 with ClientState for world -1
[03:39:46] [Server thread/INFO] [betterportals/view]: Swapping main view -556.6570124912979/69.0/753.0465266192322 with 81.5/65.0/63.5
[03:39:46] [Client thread/INFO] [betterportals/view]: Ack for swap of -1
[03:39:46] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@3eb7d374
[03:39:46] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@46f88567
[03:39:46] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@1a28a0b0
[03:39:46] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@4558f5d0
[03:39:46] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@7b67580d
[03:39:46] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@225cc14e
[03:39:46] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@3cc9ef33
[03:39:46] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@32611df2
[03:39:46] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@c192326
[03:39:46] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@677b9201
[03:39:46] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@6b654afe
[03:39:46] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@395f6917
[03:39:53] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@33d7453d
[03:39:53] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@1e15cf51
[03:39:53] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@7d941d13
[03:39:53] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@670c31e2
[03:39:53] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@6865674f
[03:39:53] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@324a8627
[03:39:53] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@53c2f5b3
[03:39:53] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@294aec95
[03:39:53] [Client thread/WARN] [minecraft/NetHandlerPlayClient]: Received passengers for unknown entity
[03:39:53] [Client thread/WARN] [minecraft/NetHandlerPlayClient]: Received passengers for unknown entity
[03:40:03] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@34859ef4
[03:40:03] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@20b45ca
[03:40:03] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@4d809f16
[03:40:03] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@377f21b3
[03:40:03] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@191d9913
[03:40:03] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@7d8e5268
[03:40:03] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@b3c6dc1
[03:40:03] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@1bc8a0a8
[03:40:03] [Client thread/WARN] [minecraft/NetHandlerPlayClient]: Received passengers for unknown entity
[03:40:03] [Client thread/WARN] [minecraft/NetHandlerPlayClient]: Received passengers for unknown entity
[03:40:04] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@4ea353d7
[03:40:04] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@231365e4
[03:40:04] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@4606e665
[03:40:04] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@17898e27
[03:40:04] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@9ddf0f4
[03:40:04] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@1ef3a47f
[03:40:04] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@b4b197f
[03:40:04] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@69f2e06d
[03:40:04] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@17337d3a
[03:40:04] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@1b01f51b
[03:40:04] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@f64f39
[03:40:04] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@6edbdf0a
[03:40:04] [Client thread/WARN] [betterportals/view]: Dropping packet net.minecraftforge.fml.common.network.internal.FMLProxyPacket@97614af`

**Comment by Johni0702** [comment] 2019-09-23 15:26
1. Are you saying that this only happens when both, RandomPatches and Nimble is installed and it doesn't happen if either is missing? Which specific versions of those mods? RandomPatches has recently had BP-specific changes.

2. Please make sure this is actually OF. I know that at least VanillaFix has a similar optimization because I've had to manually add support for both of them for the portal texture already.

3. The messages are warnings that some mod is sending packets when it probably (but not necessarily, hence warning) shouldn't, they don't seem related to portal jittering. Player positions aren't usually sent for the local player, only for other ones, so I don't see any connection there.
The issue is likely also some mod interaction (make sure RandomPatches is up-to-date!), so please try to find out which mods are relevant.

In general, please open one issue per issue. That way each one can be tracked and dealt with on its own, independent of the other ones.
Therefore I'm going to close this issue. Please open three new ones. In each one include your original paragraph and the reply to my messages above.

**Closed by Johni0702** 2019-09-23 15:26 UTC

**Comment by IdrisQe** [comment] 2019-09-23 22:09
I've made issues for the former two problems with more indepth info, visuals, and the results of some testing. The third issue, however, I think may just be due to lag, as I had a lot of mods that affected both the Overworld and Nether, which meant trying to visualize both at once was likely causing some heavy lag. I didn't notice any jittering during my tests with fewer mods enabled. It COULD be one specific mod causing issues, but testing all of them one by one would be immensely time-consuming when it's a very minimal issue only noticable when going by a portal at high speeds.

Apologies for putting the three issues in one post initially. I was tired, it was late, and didn't want to spam you with issues, although I suppose my reasoning for putting them together was flawed, as there were still the same number of issues, just in a more condensed location.
