### ISSUE TITLE
All Mixin Issues

### ISSUE THREAD

**Issue by SirStig** [Johni0702/BetterPortals#592] opened 2021-03-02 17:04 UTC
I've found a mod that I'm not seeing posted any where as a fix. But to fix a lot of bugs I've encountered with mixin use this mod.

https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility

It loads mixin before anything else and improves the compatibility of this mod with tons of others. Such as VanillaFix, and other mods that break with better portals.

If you encounter any errors about mixin install that mod listed above to fix the issue.

**Comment by Johni0702** [comment] 2021-03-02 17:17
Duplicate of #547

**Closed as completed by Johni0702** 2021-03-02 17:17 UTC
