### ISSUE TITLE
Doesnt Work with shaders

### ISSUE THREAD

**Issue by XxsjrapsxX** [Johni0702/BetterPortals#608] opened 2021-07-23 04:27 UTC
No matter what i do, attempting to use any shader i own just makes it impossible to see through as the mod intends is there some way to get around this, or are there any decent shaders that allow the portal to work? kinda confused why its not working

**Comment by Johni0702** [comment] 2021-07-23 05:07
Duplicate of #409

**Closed as completed by Johni0702** 2021-07-23 05:07 UTC
