### ISSUE TITLE
Crash w/ Mystcraft on 1.12.2 version (BP 0.3.7.7)

### ISSUE THREAD

**Issue by LtSeegson** [Johni0702/BetterPortals#521] opened 2020-05-16 20:44 UTC
Hello,
First of all, your mod is dope. 
In second place, infortunately the game crash with the error : 

> Exception ticking world

Seems to be a conflict between Mystcraft and BP. I don't know why. It still crash with third-party transfers disabled.

I've tested it with only fml, mystcraft and BP. All on latest version (05/16/2020).
It appens when joining / generating a new Age (Dimension/World in mystcraft). It just freeze and shut down the game.
I've downgraded BP to 0.3.7.5, now it works.

_Crash report :_ 
https://pastebin.com/qub5n6GM

PS : sry 4 bad english am frenchie

**Comment by LtSeegson** [comment] 2020-05-16 21:43
**EDIT : Don't work by downgrading to  0.3.7.5, had to downgrade to 0.1.4.** 
_"Exception ticking world"_ or _"Exception ticking world block"_, something with world generation. I've tested many versions, almost all, to find the latest compatible. 0.3.X simply crash, 0.2.X and 0.1.X after 0.1.4 simply dont break usage of mystcraft. (Teleportation sounds and all but still in overworld. Books dont work anymore)

**Comment by NiptheZephyr** [comment] 2020-10-25 12:54
Additionally have had issues with Mystcraft. Any word on if this is planned to be fixed? I plan to check back intermittently to see if I can add it to my modpack.

**Comment by Johni0702** [comment] 2020-10-25 14:00
No plans to fix this. For one, I've stopped working on this mod because I lost interest, but even before that (and if someone else would come along):
> However, because Mystcraft isn't open-source, it's hard to know whether this is an issue with Mystcraft's implementation or BP's.

https://github.com/Johni0702/BetterPortals/issues/330#issuecomment-529601734

**Comment by Johni0702** [comment] 2020-10-25 14:01
Duplicate of #330

**Closed as completed by Johni0702** 2020-10-25 14:01 UTC
