### ISSUE TITLE
Compatibility issues with certain mods.

### ISSUE THREAD

**Issue by ghost** [Johni0702/BetterPortals#559] opened 2020-08-26 02:52 UTC
The latest version of the BetterPortals mod for Minecraft 1.12.2 has compatibily issues with the latest versions of the Phosphor for forge mod, the Surge mod, and the VanillaFix mod. Having BetterPortals active with any of them seems to always crash the game before it can even load.

**Comment by Johni0702** [comment] 2020-08-27 05:50
Duplicate of #547

**Closed as completed by Johni0702** 2020-08-27 05:50 UTC
