### ISSUE TITLE
portal still shows particles

### ISSUE THREAD

**Issue by MechSonic** [Johni0702/BetterPortals#611] opened 2022-01-01 03:06 UTC
I was testing the mod but when I tried to light the portal It still showed the particles and still had the purple portal effect. I was able to go through it without it loading but I want to know if there is a way to fix it?

**Comment by Johni0702** [comment] 2022-01-01 07:46
Duplicate of #413

**Closed as completed by Johni0702** 2022-01-01 07:46 UTC

**Comment by MechSonic** [comment] 2022-01-03 03:02
thank you
